### ISSUE TITLE
Improvements for dcor docker approach

### ISSUE THREAD

**Issue by RaghavaAlajangi** [DCOR-dev/dcor_control#22]
In the docker approach to testing/hosting a DCOR instance, we define entry points to extend the ckan image [read here](https://github.com/ckan/ckan-docker/blob/master/README.md) with custom extensions. 

`# docker-entrypoint.d/setup_dcor.sh`
```
#!/bin/bash

pip3 install dcor_control
dcor inspect --assume-yes --dcor-site-config-dir site_dcor-docker
```
But, it has not been run because `dcor inspect` asks to enter `pgsqlpass` manually. 

Improvements:
- When I run `dcor inspect`, its asking for `pgsqlpass`. Instead of manually entering this inside the docker container, setting this as an ENV variable would be nice.
- It seems like, `dcor` excludes ckan extension `envvars` (used to set the values in `ckan.ini` from environment variables ) which is important for the Docker approach. It would be nice if `dcor_control` included this extension.
- #21

**Comment by paulmueller** [comment]
Please take a look at dcor_control 0.12.0. I believe by setting `sqalchemy.url` and `ckan.plugins` in the `dcor_config.json` already resolves this issue. You should now be able to run `dcor inspect` without any additional arguments.

If this does not work (e.g. wrong hostname or port conflicting with what is set via envvars), please use the new `dcor_site-docker/dcor_config.json` as a template and modify it to match the docker defaults.

**Comment by paulmueller** [comment]
This should also be resolved now.
